apiVersion: v1
kind: Service
metadata:
  name: edgex-core-data
spec:
  type: NodePort
  selector:
    app: edgex-core-data
  ports:
    - port: 48080
      name: port-48080
    - port: 5563
      name: port-5563
