apiVersion: v1
kind: Service
metadata:
  name: edgex-export-distro
spec:
  type: ClusterIP
  selector:
    app: edgex-export-distro
  ports:
    - port: 48070
      name: port-48070
    - port: 5566
      name: port-5566
